# -*- coding: utf-8 -*-
"""lecture8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUiNfxx0bmLQy6JjiDBb3-vw_SKMXh8_
"""

# tuple can be assigned but not copy -> latency pov faster
# retrieval of data is easy in tuple
t=(2)
a=t
print(a)
print(a*2)

#list
b=[10]
c=b
print(c)
print(c*2)

#Set -> set is ds of pytjon contains diff datatypes arrange in sequential but it have distinct val/elements
#shows only unique/distinct val
s=set((x for x in range(0,10)))
s

#methods of set
'''
1. pop() -> removes val from Start (1st index)/ removes vals from prefix
2. add() -> add values at prefix/start
'''
s.pop() # 0
s
s.pop() # 1
s

s.add(0)
s

b=s.copy()
b

a={1,1,1,1,2}
a.add(3)
a

# indexing is not allowed in SET but allowed in list and tuple
s={1,2,3}
s[0]  # error

a={x for x in range(0,10)}
print(a) #{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

# type casting a set into a list
b=list({x for x in range(0,10)})
print(b)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

c=tuple(a)
print(c)  # (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

# swapping
a=10
b=20

a,b=b,a
print(a)
print(b)