# -*- coding: utf-8 -*-
"""lecture9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sukgARQeW7lojzqiKXUHBnPKiic0nHIO
"""

'''
a set cannot be blank/datatype of blank set is dictonary
ex.
a={}
type(a)  #it is a dictonary
'''
a={}
print(type(a))

b={1,2,3}
print(type(b))

# Dictonary : dict works like a set provided cannot have duplicate keys
'''
a key can be unique
d={'key':value,
keys in distinct is always defined inside quotes('keys')
'''

#Methods of Dictonary
# 1. keys() -> gives distinct keys
# 2. values() -> gives values
# 3. items() -> gives (keys,value)
#  4. pop('key') -> removes a specific
# 5. popitem() -> removes last item

d={'india':1000,'usa':2000,'uk':3000}
print(d.keys())  #dict_keys(['india', 'usa', 'uk'])

d1 = {'india':1000,'india':2000,'uk':3000}
print(d1.keys())  #dict_keys(['india', 'uk'])

d1.values()

d1.items()

d.pop('uk')

d.popitem()
d

d={'name':'india','age':22}

d.update({'name':'manoj'})
print(d) #{'name': 'manoj', 'age': 22}

d.update({'Age':33})
print(d) #{'name': 'manoj', 'age': 22, 'Age': 33}

d.pop('Age')

#update val without update()
d['age']=42
d  #{'name': 'manoj', 'age': 42}

# list comprehension in tuple is possible
# tuple comprehension not possible in list

d=([x for x in range (0,11)])
d
type(d)

d=(x for x in range (0,11))
d

# tuple comprehension in set is not possible
# set comprehension in tuple is possible
s={(x for x in range (0,11))}
s

# Functions
# functions can be created using-> def

def hello():  # function defination
  print("Hello, how are you...")
hello()  # function calling

def greet():  # function defination
  pass  # it will not throw input error
greet()  # function calling

# wap to check wether the given string is palindrom or not

string=input("enter a string : ")
string1=string[::-1]  #reverse the string

def palindrom():
  if string==string1:
    print("it is Palindrom")
  else:
    print("it is not Palindrom")

palindrom()

def add():
  result=a+b
  print(result)

def sub():
  result=a-b
  print(result)

def mul():
  result=a*b
  print(result)

def div():
  result=a/b
  print(result)

a=float(input("enter 1st number"))
b=float(input("enter 2nd number"))
operation=input("enter + for addition\n- for subtraction\n* for multiplication\n/ for division")

if operation=='+':
  add()
elif operation=='-':
  sub()
elif operation=='*':
  mul()
elif operation=='/':
  div()
else:
  print('Invalid input')

## second way
def calculator():

  a=float(input("enter 1st number"))
  b=float(input("enter 2nd number"))
  operation=input("enter + for addition\n- for subtraction\n* for multiplication\n/ for division")

  if operation=='+':
    print(a+b)
  elif operation=='-':
    print(a-b)
  elif operation=='*':
    print(a*b)
  elif operation=='/':
    print(a/b)
  else:
    print('Invalid input')

calculator()

#wap ask user to enter string and count number of the vowels in the string

def count_vowels():

  string=input("enter a string : ")
  count=0
  for c in string.lower():
    if c=='a':
      count=count+1
    elif c=='e':
      count=count+1
    elif c=='i':
      count=count+1
    elif c=='o':
      count=count+1
    elif c=='u':
      count=count+1
  print("Total vowels count = ",count)

count_vowels()  # func calling