# -*- coding: utf-8 -*-
"""lecture5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6qmYGjRSKhvyJqvIWSVEFJoU8gH-Lz5
"""

# method -> is a function defined inside a class

### concept of pass,continue,break

#break -> exits the loop/breaking the loop
for i in range (1,5):
  print(i,end=" ")  # end = " " -> insead of going new line continue in  line (arramge elemts in horizontal)

for i in range(1,5):
  print(i,end=" ")
  break

# continue -> continues exucution
for i in range(1,5):
  print(i ,end=" ")
  continue

# continue -> statements after "continue" will be skipped and continues to the loop
# below will not print anything
for i in range(1,5):
  continue
  print(i)

# pass -> it ensure it will not throw an input error (#input error)
for i in range(1,5):
  pass

# example of pass
#use for building templates
def data_cleaning():
  pass

def data_injestion():
  pass

for i in range(1,5):
  if i % 2 == 0 :
    print(i)
    pass
  continue

i=0
while i <= 5:
  for i in range(1,5):
    pass  # nothing happens it ensures not to thorow error
    print(i)
    i += i
  break # exits the while loop

# i=0
# while i <= 5:
#   for i in range(1,5):
#     pass
#     print(i)
#     i += i
#     break # exits the for loop
# infinitely prints 1

# i=0
# while i<= 5:
#   for i in range(1,5):
#     i=i+1
#     print(i)
#     break
#   i=i+1
#   continue

i=0
while i<= 5:
  for i in range(1,5):
    i=i+1
    print(i)
  break
  i=i+1
  continue

### banking application

'''
logic:

1. ask user to enter name,passcode,acct_no,withdraw_amt,acct_type
2. defined variables: saving_acct = 10000 and current_acct = 2000
3. condition: type == 1 for saving_acct and type == 2 for current_acct
4. if withdraw_amt <= saving_acct : balance  = saving_acct - withdraw_amt
5. if withdraw_amt <= current_acct : balance  = current_acct - withdraw_amt
6. print(balance)

'''
name=input("enter your name : ")
acc_no=int(input("enter your account number : "))
passcode=int(input("enter your password : "))
withdraw_amt=float(input("enter amount to withdraw : "))
acc_type=int(input("Select account type :\n1 for Savings account \n2 for Current account"))
savings_acc=10000
current_acc=2000

if acc_type==1:
  if withdraw_amt < savings_acc :
    balance=savings_acc-withdraw_amt
    print(f"Balance : {balance}")
  else :
    print("not enough balance!")
elif acc_type==2:
  if withdraw_amt < current_acc :
    balance=current_acc-withdraw_amt
    print(f"Balance : {balance}")
  else :
    print("not enough balance!")
else :
  print("Incorrect account type.")