# -*- coding: utf-8 -*-
"""lecture6&7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XoPVeq-ijkGq7Ft8t9x0hxikuGpvwHT_
"""

# type of list -> class list

# append -> add at last ,only one value at time
# insert -> add at specific position
# extend -> insert multiple values

# pop -> remove from last
# remove -> remove from specific position
# clear -> clear the list (empty)

# copy -> create instance/object
# count(element) -> counts a specific element
# index

#even = [0 2 4 6 8]
even = []
for i in range (0,11):
  if i%2==0:
    even.append(i)
print(even)

# list comprehension -> [<expression> forloop <condition>]

even1 = [x for x in range (0,11) if x%2==0]
print(even1)

odd = [x for x in range(0,11) if x%2!=0]
print(odd)

# [0 4 16 36 64]
a=[x**2 for x in range(0,9) if x%2==0]
a

['HARSH','DEVESH','SURAJ','MAYUR']
names = ['Harsh','Devesh','Suraj','Mayur']

a=[name.upper() for name in names]
a

# Tuple

tup=()
tup
# Methods of tuple
'''
tuple is immutable i.e. we cannot add the element neither remove the element
from the tuple.
Hence, The Methods of tuple are :
1. count()
2. index()
'''
tup=(1,2,3,4,5,6,[1,(2,(3,(4,5,6),7),8),9])
# o/p - (4,5,6)
tup[6][1][1][1]   #(4,5,6)
tup[-1][-2][-2][-2]   #(4,5,6)

tup=(1,1,2,3,4,5,6,7)
tup.index(1) #0
tup.count(1) #2

# tuple comprehension
# o/p - (0,2,4,6,8,10,12,14,16,18)
tup=(i for i in range(0,21) if i%2==0)
tup #not print the tuple
# type casting the list to tuple
a=tuple([i for i in range(0,21) if i%2==0])
a

# sorting in list
num=[3,1,8,5,4]
num.sort()
print(num)  # ascending order
num.reverse()
print(num)  # descending order
# to sort a list in descending order -> 1.sort 2.reverse

# #wap to swap 2 numbers using 3rd variable
# #wap to swap 2 numbers without using 3rd var

# #using 3rd
print("using 3rd variable")

a=10
b=20
print("before swaaping : ",a," ",b)
temp=a
a=b
b=temp
print("After swapping : ",a," ",b)

# without
print("without using 3rd variable")
a=10
b=20
print("before swaaping : ",a," ",b)
a = a+b
b = a-b
a= a-b
print("After swapping : ",a," ",b)