# -*- coding: utf-8 -*-
"""lecture10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcbzdKtgvNLLBccieA7og6BLdOiXDz7t
"""

# return will not return 'none' as datatype
# Global -> scope of variable is throughout program
# Local -> scope limited to a function
i = 1
sum=100
if i<=10:
  i=sum+i
  pass
  if i<=3:
    print("Hi")
    if i<=2:
      print("world")

print(sum)

"""## code structure
1. variable defination
2. function defination
3. function calling
"""

# arguments can be defined at function defination
#
# arguments which take input from user can be written at start/prefix only then define argu. can be written/defined
a=10
def sum(num,num1=100,num2=200):
  num3=num1+num2+num
  print(num3)

sum(a) #310

sum(1,1,1)  #3

sum(a,1) #211

sum(a,num2=10)

