# -*- coding: utf-8 -*-
"""lecture3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lkb1Imray1Onzn7xEHJHd99tyb934DEV
"""

#while loop concept
i=1
while i==1:
  print(i)
  i=i+1

# for loop
#even number from 0-21
for i in range(0,21,2):
  print(i)

#odd number from 0-21
for i in range(0,21):
  if i%2==1:
    print(i)

#even number from 0-21
for i in range(0,21):
  if i%2==0:
    print(i)

#String data types
#list
str=['hello',"world","python programming"]
for i in str:
  print(i)

#tuple
str=('hello',"world","python programming")
for i in str:
  print(i)

name='India'
print(type(name))

'''
note:
when any function defined inside a class it is called
"Method of respective class"

@ -> its called decorator
'''

# Methods of String
print(name.capitalize())  #Camel casing
print(name.casefold())
print(name.lower())  # lower casing
print(name.upper())  # upper casing

# sort and reverse in List
name=[1,2,3,5,20]
name.reverse()
print(name)
name.sort()
print(name)

#sort is not applicable for alpabets
str=['a','g','d']
print(str.sort())  #not applicable

#Enumerates in python
names=['chandan','anjali','rohit','suraj']
for index,name in enumerate(names):   #enumerate() gives count and value
  print(f'Index : {index}, Name : {name}')

'''
wap salary>50000 bonus 20% ,
salary>30000 bonus 10%
salary>10000 bonus 5%
salary<10000 bonus 3%

'''
bonus=0
salary=float(input("enteer your salary"))

if salary>50000:
  bonus=salary+salary*0.2
elif salary>30000:
  bonus=salary+salary*0.1
elif salary>10000:
  bonus=salary+salary*0.05
else:
  bonus=salary+salary*0.03

print(f'Bonus = {bonus}')

