# -*- coding: utf-8 -*-
"""lecture11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpPnIL-bYhxREK88O3SHOz1jD1DihOYb
"""

'''

 class -> class is a blueprint/template of a object
 object -> object is instance of class
'''

# Concept of OOPs
# why oops -> we can write modular code
# self ->  self is special keyword,which gives access to global var
# dot operator(.) -> responsible for fetching vars/methods
class employee:

  #define constructor/special func/special method -> its a special method used to define global variables
  # constructor can be defined by -> __init__() -> double underscore
  # constructor responsible for binding all
  def __init__(self,name,age,designation):
    self.name=name
    self.age=age
    self.designation=designation

  # method to print vars
  def display(self):
    print(self.name,self.age,self.designation)


# define object : employee
emp1=employee('Devesh',29,"HR")
emp2=employee('Sooraj',28,'Developer')

print(emp1.name)
print(emp2.name)
print(emp2.age)

print(emp1.display())

# define class
class itv:

  #define constructor
  def __init__(self,
               course,
               name,
               age,
               duration):

    self.course=course
    self.name=name
    self.age=age
    self.duration=duration


# define object
obj1=itv("JFSD","Namit",22,6)
obj2=itv("DSDA","Sumit",21,8)
obj1=itv("JFSD","Neha",27,6)
obj1=itv("DSDA","Riya",24,8)


print(obj1.course,obj1.name,obj1.age,obj1.duration)

class car:

  def __init__(self,
               wheel,
               model,
               capacity,
               color):

    self.wheel=wheel
    self.model=model
    self.capacity=capacity
    self.color=color

  def mileage(Self):
    mileage=f"mileage is 15"
    return mileage



obj1=car(4,'Petrol',4,'red')

print(obj1.wheel)
print(obj1.capacity)
print(obj1.model)

print(obj1.mileage())

