# -*- coding: utf-8 -*-
"""pandas_lecture4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtjkUadjl-8KgOq4vkNxnuyL_BACYJOK
"""

# Lecture 4 part 2

# Import data manipulation library
import numpy as np
import pandas as pd

# import data visualization library
import matplotlib.pyplot as plt
import seaborn as sns

# step1: Data Ingestion

def data_ingestion(data):
  df=pd.read_csv(data)
  return df

# step2: Descriptive stats

def descriptive_stats(df):

  from collections import OrderedDict
  stats=[]

  for i in df.select_dtypes(exclude='object'):
    numerical_stats=OrderedDict({
        'Feature':i,
        'Count':df[i].count(),
        'Maximun':df[i].max(),
        'Minimun':df[i].min(),
        'Mean':df[i].mean(),
        'Median':df[i].median(),
        'Q1':df[i].quantile(0.25),
        'Q3':df[i].quantile(0.75),
        'IQR':df[i].quantile(0.75)-df[i].quantile(0.25),
        'Std':df[i].std(),
        'Skew':df[i].skew(),
        'Kurtosis':df[i].kurtosis()
    })
    stats.append(numerical_stats)
  report=pd.DataFrame(stats)
  return report

#
def dataset_information(df):
  info=df.info()
  duplicated_values=df.duplicated().sum()
  null_values=df.isnull().sum()
  return info,duplicated_values,null_values

# shows the info in one
def cross_tab(row,col):
  x=pd.crosstab(index=row,columns=col,margins=True).plot(kind='bar')
  return x

from pandas.core.reshape.pivot import crosstab
# Define Entry point

def main():  # entry point method/main method
  df=data_ingestion('/content/titanic_dataset.csv')
  # report=descriptive_stats(df)
  # info,duplicated_values,null_values=dataset_information(df)
  print(cross_tab(df['Sex'],df['Survived']))

main()

