# -*- coding: utf-8 -*-
"""pandas_lec2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDTKtWoKzo3024ulfZEh9qyYpWFUbTL8
"""

# Lecture 2
'''
'''

import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Name':['A','B','C','D','E','F'],
    'Department':['HR','IT','SALES','HR','IT','SALES'],
    'Age':[42,46,56,50,27,39],
    'Salary':[1000,4000,6000,8000,3000,9000],
    'Experience':[2,4,6,3,5,7]
})

df

# Descriptive Stats: Methods 1
df.describe()



# Descriptive Stats: Methods 2
from collections import OrderedDict

stats=[]
for i in df.select_dtypes(exclude='object'):

  numerical_stats=OrderedDict({
      'Feature':i,
      'Count':df[i].count(),
      'Maximun':df[i].max(),
      'Minimum':df[i].min(),
      'Mean':df[i].mean(),
      'Median':df[i].median(),
      'Q1':df[i].quantile(0.25),
      'Q3':df[i].quantile(0.75),
      'IQR':df[i].quantile(0.75)-df[i].quantile(0.25),
      'Lower Whiskers':df[i].quantile(0.25)- 1.5*df[i].quantile(0.75)-df[i].quantile(0.75),
      'Upper Whiskers':df[i].quantile(0.75)+ 1.5*df[i].quantile(0.75)-df[i].quantile(0.75),
      'Std':df[i].std(),
      'Skewness':df[i].skew(),
      'Kurtosis':df[i].kurt()
  })
  stats.append(numerical_stats)
  report=pd.DataFrame(stats)

report

df = pd.DataFrame({
    'Name':['A','B','C',np.nan,'E',np.nan],
    'Department':['HR','IT','SALES','HR',np.nan,np.nan],
    'Age':[42,46,np.nan,50,np.nan,39],
    'Salary':[1000,np.nan,6000,8000,3000,np.nan],
    'Experience':[2,4,6,3,8,7]
})

import matplotlib.pyplot as plt

df.isnull().sum().plot(kind='bar',color='y')
plt.title("Graph Showing Missing Values Information")
plt.show()

'''
Imputing Null values in data using
  -> .fillna()

'''
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df['Age']=df['Age'].fillna(df['Age'].median())
df['Department']=df['Department'].fillna(df['Department'].mode()[0])
df['Name']=df['Name'].fillna('X')

df

employee_data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Karan', 'Neha', 'Vijay', 'Pooja', 'Rohit', 'Anjali'],
    'Age': [25, 30, np.nan, 28, 35, np.nan, 40, 29, 31, 27],
    'Department': ['HR', 'IT', 'Finance', np.nan, 'IT', 'HR', 'Finance', 'Marketing', np.nan, 'IT'],
    'Salary': [45000, 60000, 55000, np.nan, 70000, 48000, np.nan, 52000, 61000, 58000],
    'Experience': [2, 5, 4, 3, np.nan, 2, 10, 4, 6, np.nan],
    'Performance_Rating': [4.5, 4.8, np.nan, 4.2, 4.9, 4.1, 5.0, np.nan, 4.6, 4.3]
}


df = pd.DataFrame(employee_data)

df



from collections import OrderedDict
stats_num=[]
stats_cat=[]

for i in df.select_dtypes(exclude='object'):
  numerical_stats=OrderedDict({
      'Feature':i,
      'Count':df[i].count(),
      'Maximun':df[i].max(),
      'Minimun':df[i].min(),
      'Mean':df[i].mean(),
      'Median':df[i].median(),
      'Q1':df[i].quantile(0.25),
      'Q3':df[i].quantile(0.75),
      'IQR':df[i].quantile(0.75)-df[i].quantile(0.25),
      'Standard Deviation':df[i].std(),
      'Skewness':df[i].skew(),
      'Kurtosis':df[i].kurt()

  })
  stats_num.append(numerical_stats)
  num_report=pd.DataFrame(stats_num)

num_report

for i in df.select_dtypes(include='object'):
  categorical_stat=OrderedDict({
    'Feature':i,
    'Count':df[i].count(),
    'Mode':df[i].mode()[0],
    'Null val Count':df[i].isnull().sum()


  })
  stats_cat.append(categorical_stat)
  cat_report=pd.DataFrame(stats_cat)

cat_report

df['Department']=df[df['Department']=='HR'].fillna("X")
df['Department']