# -*- coding: utf-8 -*-
"""pandas_lec1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I64SagaTrUn9viObdGQu4LbiEJO0EH3Z
"""

'''
Methods of Pandas :
  .head() -> return top 5 rows
  .head(2) -> return top 2 rows
  .tail() -> return bottom 5 rows
  .tail(2) -> return bottom 2 rows
  .sample(frac=1) -> return random rows

  .info() -> return information about data (row count,column count,
    data type of each column,total null values)
  .describe() -> return statistical information about data
  .isnull() -> checks the null valus (in Boolean vals)
  .isnull().sum() -> return count of all null values in each column
  .loc[] -> return value of specific row and column
  .iloc[] -> return value of specific row and column by index
'''

# Pandas Lecture 1

'''
Series :
  used to create a 1-D array

  attributes :
    index=[] -> define index for elements by default from zero.
    ex,
    a=pd.Series([1,2,3,4],index=['a','b','c','d'])

'''
import numpy as np
import pandas as pd

a=pd.Series([1,2,3,4],index=['a','b','c','d'])
print(a)

# Creating 2-D array
'''
DataFrame :
  used to create 2D array

  attributes :
    index=[] -> define index for elements by default from zero.
    columns=[] -> define columns for elements by default from zero.


'''

b=pd.DataFrame([1,2,3,4],columns=['value'],index=['a','b','c','d'])
print(b)

data=pd.DataFrame({'India':[10,20,30,40],
                   'USA':[40,60,70,90],
                   'UK':[100,200,120,300]})

data['India'].sum(),data['India'].mean(),data['India'].median()

# calculate IQR,LW,UW
q1 = data['India'].quantile(0.25)
q3 = data['India'].quantile(0.75)

iqr = q3 - q1
lw = q1 - 1.5 * iqr
uw = q3 + 1.5 * iqr

print(q1,q3,iqr,lw,uw)

'''
Methods of DataFrame :
  .quantile(0.75)
  .skew() -> return skewness value
  .kurt() -> return kurtosis value
  .plot() -> plot the graph
  .plot(kind='kde') -> plot the density graph

'''

# skewness and kurtosis
skew_ind=data['India'].skew()
kurt_ind=data['India'].kurt()
skew_ind,kurt_ind

import matplotlib.pyplot as plt

data['India'].plot(kind='kde')
plt.axvline(25,color='r',linestyle='--')
plt.axvline(32.5,color='g',linestyle='--')
plt.axvline(17.5,color='g',linestyle='--')
plt.axhline(0.005,color='b',linestyle='--')
plt.show()

data.head()

data.head(2)

data.tail()

data.tail(2)

data.sample(frac=1)

data.info()

data.describe()

# checking null values using stats method

data.isnull().sum()

# checking null values using graphical method

data.isnull().sum().plot(kind='bar')
plt.title("Graph showing Null Values")
plt.show()

data

# data.loc[]
data.loc[0,'UK']

# data.iloc[row_index, column_index]
data.iloc[0,2]

df = pd.DataFrame({'Gender':['Male','Female','Male','Female'],
                   'Station':['Thane','kalyan','Bhandup','Diwa'],
                   'Age':[50,70,90,45],
                   'Salary':[1000,3000,5000,7000]})
df

# Filtering data

male_data=df[df['Gender']=='Male']
male_data

Female_data=df[df['Gender']=='Female']
Female_data

from matplotlib.lines import lineStyles
df['Gender'].value_counts().plot(kind='pie',
                                 autopct='%0.2f',
                                 explode=[0.02,0.02],
                                 title="Gender Distribution Graph")
plt.show()