# -*- coding: utf-8 -*-
"""lecture_numpy2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADCA_VD2-7tEZjQDHzp_D2M4713uae5z
"""

import numpy as np

a=np.array([1,2,3])
a.ndim   # .ndim -> it shows the dimension of an Array
a.shape  # .shape -> it shows (m,n) [m -> no, of rows , n -> no. of columns]

a1=np.array([[1,2,3],[4,5,6]])
print(a1.ndim)
print(a1.shape)

a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2.shape)

# Transpose of matrix
print(a2)
print()
print(a2.T)  # .T converts into transpose

a2.flatten()  # converts 2D into 1D

a2.sum()  # sum() -> gives sum of all elements

a2.sum(axis=1) # axix=1 -> row wise sum

a2.sum(axis=0)  # axix=0 -> column wise sum

a2.max(),a2.min(),a2.mean()

np.eye(5)  # it creates a Identity matrix of '5x5'

np.eye(3)  # it creates a Identity matrix of '3x3'

np.zeros(3) # creates a 1D array of zeros(0) with length 3

np.zeros(5) # creates a 1D array of zeros(0) with length 5

np.ones(3)  # creates a 1D array od ones(1) with length of 3
np.ones(5)  # creates a 1D array od ones(1) with length of 5

array4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array4.shape)

array4.reshape(2,6)  # reshape(m,n) -> converts the matrix into desired shape
# chamge the dimension

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a+b)
print()
print(a-b)
print()
print(a/b)
print()
print(a*b)

print(a*20) # multiplies each element of matrix by 20

print(a>1)   # comapres each element of matrix to 1 and returns a boolean

# variance -> spread among data points
# std deviation -> under root of variance
#               -> deviation of each and every data points wrt mean

np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

x=np.array([1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15,16,17,18,19,20,
            21,22,23,24,25,26,27,27,29,30,
            31,32,33,34,35]).reshape(7,5)

x
print(x[2:5,1:4])

y=np.arange(1,36).reshape(7,5)  # np.arange(start, end, step)
y

z=np.arange(1,36,2).reshape(3,6)  # np.arange(start, end, step)
z

d=np.linspace(0,100,5,dtype='int')   # np.linspace(start, end, partition_number, dtype='int') by default float
d

# Random
np.random.seed(0)   # locks the random values
a=np.random.rand(3,3)
a

np.random.randint(low=0,high=1,size=(3,3))

'''
1. when mean = median then distribution is
symmetric/normally distributed/no skew distribution.

2. when mean > median then distribution is positively skewed.
3. when mean < median then distribution is negatively skewed.
'''
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

np.median(a),np.mean(a),np.std(a),np.var(a),np.max(a),np.min(a)