# -*- coding: utf-8 -*-
"""lecture_WebScrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TTpOml9TMtMesJRRLD-E34FhhmC1H_k
"""

#task1


from abc import ABC


# Parent Class
class AJSB(ABC):

    def __init__(self, name, age, gender, address, acc_no, password):
        self.name = name
        self.age = age
        self.gender = gender
        self.address = address
        self.acc_no = acc_no
        self.__password = password


# Savings Account
class SavingsAcc(AJSB):

    def __init__(self, name, age, gender, address, acc_no, password, interest_rate):
        super().__init__(name, age, gender, address, acc_no, password)
        self.interest_rate = interest_rate


# Current Account
class CurrentAcc(AJSB):

    def __init__(self, name, age, gender, address, acc_no, password, overdraft_limit):
        super().__init__(name, age, gender, address, acc_no, password)
        self.overdraft_limit = overdraft_limit


# NRI Account
class NRIAcc(AJSB):

    def __init__(self, name, age, gender, address, acc_no, password, currency_type):
        super().__init__(name, age, gender, address, acc_no, password)
        self.currency_type = currency_type


# Create Objects

savings = SavingsAcc(
    "Kuldeep",
    21,
    "Male",
    "Ambernath",
    1234,
    3333,
    0.9
)

current = CurrentAcc(
    "Rahul",
    25,
    "Male",
    "Mumbai",
    5678,
    4444,
    60000
)

nri = NRIAcc(
    "Amit",
    30,
    "Male",
    "Dubai",
    9999,
    5555,
    "USD"
)


# Output
print("Savings Account Holder:", savings.name)
print("Interest Rate:", savings.interest_rate)
print("age : ",savings.age)

print("Current Account Holder:", current.name)
print("Overdraft Limit:", current.overdraft_limit)

print("NRI Account Holder:", nri.name)
print("Currency Type:", nri.currency_type)

# step1: data loading/data ingestion

# step2: data exploration: eda / exploratory data analysis

# step3: data cleaning / data preprocessing

# step4: data transformation

# step5: data modeling

# step6: Results/model deployment

import pandas as pd

def data_ingestion(data):
  df = pd.read_csv(data)
  return df

def data_exploration():
  pass

def data_cleaning():
  pass

def data_transformation():
  pass

def data_modeling():
  pass

def model_deployment():
  pass

# define entry point

def main():
  df = data_ingestion('data.csv')
  data_exploration(df)
  data_cleaning(df)
  data_transformation(df)
  data_modeling(df)
  model_deployment(df)

main()

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Website URL
url = "https://www.aajtak.in/&quot;"

# Get HTML content
response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

news = []

for link in soup.find_all("a"):
    title = link.text.strip()
    href = link.get("href")

    # Store only valid data
    if title and href:
        news.append([title, href])

df = pd.DataFrame(news, columns=["Title", "URL"])

df = df.drop_duplicates()

df.to_csv("aajtak_news.csv", index=False)

print("CSV file created successfully!")

'''
numpy = numerical + python
Numpy -> It is a vectorized form of an array.
  - why numpy -> It is faster in computation.
  - vectorized form or an array is a N dimensional array
'''

import numpy as np

a = np.array([2])
print(type(a))
print(a.ndim)

b=np.array([[1,2]])
print(type(b))
print(b.ndim)

c=np.array([[[1,2]]])
print(type(c))
print(c.ndim)