# -*- coding: utf-8 -*-
"""lecture3_numpy&stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMhMFM6jBZY-tLb8dg6yR0Zs2QHH5E1P
"""

# Numpy lecture 2
# shape -> return rows and columns(m,n)
# rshape -> change the structure of matrix
import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]).reshape(4,5)
array
array[1:3,3:5]  # array[1:3,-2:]

'''
 Statistics :
    1. Descriptive stats : count,max,min,avg,kurtosis,std,var etc...
    2. Inferential stats : Hypothesis Testing
'''
'''
Statistics mainly consists of following steps...
  step1: collect data
  step2: organizing data  (sorting)
  step3: summarized data
  step4: inferential stats
'''

a=[1,8,32,30,90,65]
a.sort()
a

'''
Central tendency refers to the numerical value that represents the "center" or
"typical" observation within a dataset.

Central tendency are of 3 types...
  1. mean : average
  2. median : central value
  3. mode : most frequent occuring value

note1:
a. mean and median generally used for numerical columns
b. mode generally used for categorical columns

'''

'''
note2:
when mean = median then such distribution is called Normally distributed data.
this distribution is also called symmetrric distsribution

note3:
when mean > median then such distribution is called positively skewed data.

note4:
when mean < median then such distribution is called negatively skewed data.

'''
array = np.array([1,2,3,4,5,6,7,8,9,10])
mean=np.mean(array)
print(f"The mean value of array is {mean}")
median=np.median(array)
print(f"The median value of array is {median}")

arr1=np.array([100,400,700,300,200,100,800,900])
updated_arr1=np.sort(arr1)
mean=np.mean(updated_arr1)
median=np.median(updated_arr1)

print(f"mean= {mean}, median= {median}")

''' Methods to replacing Outliers

1. capping :
      1. big diff btn mean & median -> outliers/median
      2. marginal diff btn mean & median -> outliers/mean or median

2. trim :
      -> removing outliers vals

arr1=np.array([100,400,700,300,200,100,800,900])
max_val=np.max(arr1)
min_val=np.min(arr1)

range=max_val-min_val
print(f"The range of array is {range}")

# calculate variance
# std -> diffrence of data points wrt to mean
variance=np.var(arr1)
print(variance)

std=np.sqrt(variance) # 299.739470207045
std1=np.std(arr1)  # 299.739470207045
print(std)
print(std1)

# IQR -> inter queartile range

q1 = np.percentile(arr1,25)
q3 = np.percentile(arr1,75)

iqr=q3-q1
print('Inter Quartile Range is =',iqr)