# -*- coding: utf-8 -*-
"""Numpy_lecture7&8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtPvfOEaYnCBaO92MwRgbfVPbczqfchl
"""

# Lecture 7
'''
Samples -> a chunk of data, represents the population.
-> to take samples always take 10% or 5% from population
-> if sample size > 30 use Z-test ,  if sample size < 30 use t-test

# types of sampling :
  -> simple random sampling
  -> stratified sampling
  -> cluster sampling
  -> systematic sampling
  -> convenience sampling

# data sample have high errors then data is not Reliable
'''
'''
SE (Standard Error):
# standard error = stddev/sqrt(n)
# to decrease standard eror, increase the sample size.

'''
'''
Hypothesis Testing
  2 type:
  ->Null Hypothesis (H0)
  ->Alternative Hypothesis(Ha)

  Note:
    if p < 0.05 rejects null hypothesis
    if p > 0.05 accepts null hypothesis
'''

# Lecture 8
'''
*CLT -> Central Limit Theorem :
  sampling distribution

  Note:
    -> higher the sample size, lower the IQR/CI
    -> higher the sample size, lower the spread/distribution
    -> as sample size increases, distribution becomes normal (Mesokurtic)
    -> here n(sample size) must be greater than 30, i.e. n>30
    -> if data is already normal then we can take less sample also.(n=30)

  limits:
    -> requires independence.
    -> requires random sample.
    -> not work for extreme small values.
    -> not well for extremely skewed/heavy tailed data.
'''
'''
Terminology:
'''


'''
MOE(Margin of Error) = critical value * std.error(SE)
ex, 50% +- 3%

'''

# solving one sample t-test using scipy module.
from scipy.stats import ttest_1samp
import numpy as np
#sample 12
marks=np.array([8,9,8,8,8,8,8,8,8,8,8.5,8])
mean=np.mean(marks)

'''
H0: The mean avh marks score by learners =8
Ha : The mean avh marks score by learners !=8
'''
t_statistics,p_value=ttest_1samp(marks,8)
print(f"The p value is {p_value}")
if p_value<0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

# example to solve
'''
a client claims that the consinement is faulty as the standard pH value
is not equal to 7. so prepare inferencial stats report to support the
claim.
'''
import numpy as np
from scipy.stats import ttest_1samp

test_report=[7,7.1,7.2,7,7,7,7,7,8,8,9,10,7.2,9,7.2,7,7,7,7]
test=np.array(test_report)
length=len(test)
mean=np.mean(test)
print('mean is',mean)  # 7.510526315789473
print('sample size is',length)
'''
H0=company mean avg = 7
Ha=mean avg != 7
'''
t_ststs,p_val=ttest_1samp(test,7)
print(f"The p value is {p_val}")
if p_val<0.05:
    print("Reject Null Hypothesis ie accept alternative hypothesis")
else:
    print("Accept Null Hypothesis ie rejet the alternative hypothesis")

sd=np.std(test)
sqrt_sample=np.sqrt(length)
se=sd/sqrt_sample
print("Standard error = ",se)

ub=7+se
lb=7-se
print("upper bound =",ub,"Lower bound =",lb)