# -*- coding: utf-8 -*-
"""Numpy_lecture5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kijk0PYlJWGRQJjzaAA3_m8aNFkISkwZ
"""

# Lecture 5

'''
correlation :
relation betn 2 var : (x,y)
r^2 = 1<x<-1
eqn of line -> y=-m*x+c
c -> distance of line from origin
if c=0, then y=mx ,
theta(0)=tan^-1(m)

eqn of slope -> m = (y2-y1)/(x2-x1)
if r^2=1
x dir.proportional y

similarly r^2=-1
x inversely y


'''

'''
Correlation =[ covariance(x,y)/std dev ]
correlation is numeric val i.e. 1<x<-1.

covariance is not a quantitative value,
it can be +ve ,-ve or zero.
'''

'''
#Measures of Association

a. covariance
b. correlation = (covariance/std)

Note:
1. In order to evaluate correlation please ensure all the columns are in one
scale.

2. There are 3 tyoes of scaling technique
    - Standard scaler
    - MinMax scaler
    - Robust scaler

    Note :
    a. When the dataset is normally distributed (symmetric data) then go for
    stamndard scaler.
    b. When the dataset is non normally ditributed (skewed data) then go for
    MinMax scaler.
    c. When dataset is non normally distributed also containing lot of
    outliers i.e. outliers makes the machine Leaerning model sensitive then
    only go for robust scaler.

'''
'''
# when columns have IQR = 0 i.e. q1=q3 then drop that column.
'''

'''
#Skewness
  skewness is classified in to 3 types :
    - Positive skewness
    - Negative skewness
    - Zero skewness (no skewed/symmetric  distribution)

'''

'''
#Kurtosis
  3 types of kurtosis :
    - platy kurto
    - meso kurto (normally distribution)
    - lepto kurto

'''