# -*- coding: utf-8 -*-
"""Numpy_lecture9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/115rU2Ef6lSlPk3nvMr_-sefZ1fD7Dntk
"""

# Lecture 9
'''
higher the sample size , precise the result
precision : closeness to the result
accuracy :
ex, Dart game
'''

'''
smaller p val -> stronger evidence -> reject null
p_value can never be 0.05 ,
if p_value=0.05 then increase sample size.
'''

'''
When to use z-test :
  -> sample > 30
  -> *population SD is known.

  formula :
    Z = (xbar - mew)/(sigma - sqrt(n))
    where :
      xbar = sample mean
      mew = population mean
      sigma = population SD
      n = sample size

  z-score must betn (-3 to 3)

'''

'''
When to use t-test
  -> n<=30
  -> SD is unknown
formula :
    Z = (xbar - mew)/(S - sqrt(n))
    where :
      xbar = sample mean
      mew = population mean
      S = sample SD
      n = sample size
'''

'''
TYPE 1 error (False Positive)
  actual h0 is true,but reject h0
TYPE 2 error (False Negative)
  actual h0 is false,accept h0
'''

#example

import numpy as np
from scipy.stats import ttest_1samp

test=np.array([500,500,501,502,500,503,510,522,530,540,501,500,500,501,502,503,504])
length=len(test)
print("sample size is",length)
mean=np.mean(test)
print("mean is",mean)

'''
h0=500
ha!=500
'''

t_test,p_val=ttest_1samp(test,500)
print("p value is",p_val)

if p_val<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

# Two sample t test
from scipy.stats import ttest_ind
import numpy as np

suraj=[500,501,500,500,500,501,502,506,501,500,500,500,501,500,500]
sansk=[500,501,500,500,500,501,500,500,501,500,500,500,500,500,500]

s1=np.array(suraj)
s2=np.array(sansk)

t_test,p_val=ttest_ind(s1,s2)
print("p value is",p_val)

if p_val<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

print(int(np.mean(s1))==int(np.mean(s2)))