# -*- coding: utf-8 -*-
"""Numpy_lecture4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmP-F6E8z7Kqe-6CMbaLh6JX_hs4MMDf
"""

# IQR
# Lower whisker = (Q1 - 1.5*IQR)
# Upper whisker = (Q3 + 1.5*IQR)

import numpy as np
array=np.array([100,400,700,300,200,100,800,900])
q1=np.percentile(array,25)
q3=np.percentile(array,75)

iqr=q3-q1
print("IQR = ",iqr)

lowerWhisker=q1-1.5*iqr
upperWhisker=q3+1.5*iqr

print("Lower Whisker =",lowerWhisker)
print("Upper Whisker =",upperWhisker)

# calculate outlierws for this:
arr2=np.arange(1,10,1)
q1=np.percentile(arr2,25)
q3=np.percentile(arr2,75)

iqr=q3-q1
print("IQR = ",iqr)

lowerWhisker=q1-1.5*iqr
upperWhisker=q3+1.5*iqr

print("Lower Whisker =",lowerWhisker)
print("Upper Whisker =",upperWhisker)

# Measure of Dispersion (range)

'''
The methods used for evaluation of outliers are as follows:
1. IQR method
2. z-test

Note:
1. If the dataset contains outliers check the numner  of outliers present in
the given dataset.(Ideally allowable outliers percentage must be 5%)
2. if outliers are less than 5% then we can use capping method.
3. if outliers are more than 5% then we can use IQR method.
4. if outliers are more than 10% then we can use z-test.
5. some poeple also use Winsorization technique to handle outliers.
6*. as far as possible avoid trimming technique.
7. if data is not normally distributed or skewed than better  to use IQR  method
rather than winsorization technique.
8. is the dataset is highly skewed then use box-cox technique or Yeo Jhonson meyhod or
log normal method in orde to convert high skewed data into normal distribution. Then
only think of outlier treatment decision.
9. you may use shapiro tst to check whether the dataset is normally
distributed or not.


Note :

z score can be evaluated as :( (x-mean)/std deviation )
outliers = zscore =>3 or zscore =>-3
'''
# z-test used only for normally disttributed data
# outlier using z-score
import pandas as pd
from scipy.stats import zscore

data = [5,2,4,20,3,6,4,1,0,7,9,2.5,3.2,1.7,6.4]
df=pd.DataFrame(data)

df['zscore']=zscore(data)
df

# outlier using IQR (numpy)
df=np.array(data)
df

q1=np.percentile(df,25)
q3=np.percentile(df,75)

iqr=q3-q1
lowerWhisker=q1-1.5*iqr
upperWhisker=q3+1.5*iqr

print("Lower Whisker =",lowerWhisker)
print("Upper Whisker =",upperWhisker)

# exercise
array3=np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
arr4=array3.ravel()

q1=np.percentile(arr4,25)
q3=np.percentile(arr4,75)

iqr=q3-q1
lowerWhisker=q1-1.5*iqr
upperWhisker=q3+1.5*iqr

print("Lower Whisker =",lowerWhisker)
print("Upper Whisker =",upperWhisker)

# CV -> Coefficient of variance = (var/mean)